### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by pizixi** [atopos31/go-veilink#1]
小巧好用，有如下几点建议
1、客户端和服务端通讯加密
2、增加socks5协议
3、服务端是否可以动态添加/删除配置，这样可以弄个简单页面添加或删除配置
4、同一个客户端不能开多个tcp端口

**Comment by atopos31** [comment]
感谢建议。
1.考虑使用[chacha20 加密算法](https://pkg.go.dev/golang.org/x/crypto/chacha20)对TCP协议进行流式加密。
